### ISSUE TITLE
Didn't get code on MacOS

### ISSUE THREAD

**Issue by IshaanOhri** [machester4/vupc#5]
![image](https://user-images.githubusercontent.com/39885197/108015669-c0325100-7036-11eb-9fa5-11d5ae1ab390.png)

Tried running the application on macOS (v 11.2), but didn't get any code on the screen.

**Comment by machester4** [comment]
Hi @IshaanOhri for signaling app use `https://vupc.herokuapp.com` now it's down. You can set up a local server and change this parameter in [this file](https://github.com/machester4/vupc/blob/master/app/src/core/signaling/signaling.js)
